// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvsuofcvwokfndlnbwbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2c3VvZmN2d29rZm5kbG5id2JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzM2NzYsImV4cCI6MjA3MzcwOTY3Nn0.XqL-ISH1__hncYN9iyouwzZdryFBOnrUCssRs7rLHdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});